import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import styles from './screens.module.css';
export const PantallaDetalle = ({ state, dispatch, }) => {
    if (!state.programa || !state.ejercicioSeleccionado) {
        return _jsx("div", { children: "Ejercicio no seleccionado" });
    }
    const ejercicio = state.programa.ejercicios.find((e) => e.id === state.ejercicioSeleccionado);
    if (!ejercicio) {
        return _jsx("div", { children: "Ejercicio no encontrado" });
    }
    return (_jsxs("div", { className: styles.screen, children: [_jsxs("div", { className: styles.header, children: [_jsx("h1", { children: ejercicio.nombre }), _jsx("button", { className: styles.buttonSmall, onClick: () => dispatch({ type: 'CAMBIAR_PANTALLA', payload: 'rutina' }), children: "\u2190 Volver" })] }), _jsxs("div", { className: styles.card, children: [_jsxs("p", { className: styles.metadata, children: [ejercicio.minutos_estimados, " min \u2022 ", ejercicio.pilar] }), _jsxs("p", { className: styles.evidencia, children: ["Nivel: ", ejercicio.nivel_evidencia] })] }), _jsx("div", { className: styles.svgBox, children: _jsxs("svg", { viewBox: "0 0 200 200", className: styles.exerciseSvg, children: [_jsx("circle", { cx: "100", cy: "60", r: "20", fill: "#3b82f6", opacity: "0.3" }), _jsx("rect", { x: "85", y: "85", width: "30", height: "60", fill: "#3b82f6", opacity: "0.3" }), _jsx("line", { x1: "100", y1: "145", x2: "70", y2: "180", stroke: "#3b82f6", strokeWidth: "4", opacity: "0.3" }), _jsx("line", { x1: "100", y1: "145", x2: "130", y2: "180", stroke: "#3b82f6", strokeWidth: "4", opacity: "0.3" }), _jsx("text", { x: "100", y: "195", textAnchor: "middle", fontSize: "12", fill: "#6b7280", children: ejercicio.nombre })] }) }), _jsxs("div", { className: styles.card, children: [_jsx("h2", { children: "\uD83D\uDCDD Instrucciones" }), _jsx("p", { className: styles.instructionText, children: ejercicio.instrucciones })] }), ejercicio.senales_correctas && (_jsxs("div", { className: styles.card, children: [_jsx("h3", { className: styles.signalCorrect, children: "\u2713 Se\u00F1ales de ejecuci\u00F3n correcta" }), _jsx("ul", { className: styles.signalList, children: ejercicio.senales_correctas.map((señal, i) => (_jsx("li", { children: señal }, i))) })] })), ejercicio.senales_error && (_jsxs("div", { className: styles.card, children: [_jsx("h3", { className: styles.signalError, children: "\u26A0 Se\u00F1ales de error" }), _jsx("ul", { className: styles.signalList, children: ejercicio.senales_error.map((señal, i) => (_jsx("li", { children: señal }, i))) })] })), _jsx("button", { className: styles.buttonPrimary, onClick: () => dispatch({ type: 'CAMBIAR_PANTALLA', payload: 'guia' }), children: "Realizar ejercicio \u2192" })] }));
};
